repos:
- repo: local
  hooks:
    - id: nbdime-local
      name: nbdime (local)
      entry: nbdime
      language: system
      files: '\\.ipynb$'

    - id: nbstripout-local
      name: nbstripout (local)
      entry: nbstripout
      language: system
      files: '\\.ipynb$'

    - id: clean-notebook-ids
      name: Remove notebook cell ids
      entry: python scripts/clean_notebook_ids.py
      language: python
      files: '\\.ipynb$'